//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorlinkTrading.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceNonVat
    {
        public int InvoiceNumber { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string Reference { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string DisplayValue { get; set; }
        public string ExtraDetails { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedByUserName { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedByUserName { get; set; }
    }
}
