//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorlinkTrading.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaFile
    {
        public int MediaFileId { get; set; }
        public string MediaGUID { get; set; }
        public string MediaDescription { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedByUserName { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedByUserName { get; set; }
    }
}
