//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorlinkTrading.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> RandPricePreVat { get; set; }
        public Nullable<decimal> RandPricePostVat { get; set; }
        public Nullable<decimal> RandPricePostMarkup { get; set; }
        public Nullable<decimal> CashPrice { get; set; }
        public Nullable<decimal> VatAmount { get; set; }
        public Nullable<decimal> PriceIncVat { get; set; }
        public Nullable<decimal> CompetitorPrice { get; set; }
        public string Comments { get; set; }
        public string CompetitorDetails { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<decimal> MarkUpPercentage { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedByUserName { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedByUserName { get; set; }
    }
}
