//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorlinkTrading.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        public int UserId { get; set; }
        public string UserGUID { get; set; }
        public int PersonId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string EncryptedPassword { get; set; }
        public Nullable<System.DateTime> LastPasswordChangeDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<int> FailedLoginAttempts { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedByUserName { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedByUserName { get; set; }
        public Nullable<System.DateTime> TermsAndConditionsAcceptDate { get; set; }
        public Nullable<System.Guid> RequestGuid { get; set; }
        public Nullable<bool> IsRequestGuidExpired { get; set; }
        public Nullable<System.DateTime> RequestGuidExpiryDate { get; set; }
        public int FailedPasswordAttempts { get; set; }
        public Nullable<System.DateTime> AccountLockoutDate { get; set; }
    }
}
