//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorlinkTrading.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_NonVatInvoices
    {
        public string ProductName { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string CustomerName { get; set; }
        public string Reference { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public string ExtraDetails { get; set; }
        public string DisplayValue { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public int InvoiceNumber { get; set; }
        public int ProductInvoiceNonVatId { get; set; }
        public Nullable<int> InvoiceNo { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> ProdId { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
